# Direcciones de Newton

In [1]:
from derivatives import hessian
from functions import rosenbrock, uneven_paraboloid
from descentMethods import max_descent, newton_descent
import numpy as np

In [2]:
def f_prueba(x):
    x1 = x[0]
    x2 = x[1]
    fx = (x1**2)*(x2**2) + 8*(x1)*(x2)
    return fx

In [3]:
x = np.array([1., 1.])
print(hessian(f_prueba, x))

[[ 1.9999824  12.00001876]
 [12.00001876  1.9999824 ]]


In [4]:
x = np.array([1., -1.])
print(hessian(f_prueba, x))

[[2.00000017 4.00000033]
 [4.00000033 2.00000017]]


In [5]:
x = np.array([1., 1.])
print(hessian(rosenbrock, x))

[[ 800.02400015 -400.00200001]
 [-400.00200001  202.        ]]


### After the little change in direction in descent, we can try out our Netwon Method

Testing on the uneven paraboloid

In [6]:
x = np.array([1.3, -0.8])
x, k = max_descent(uneven_paraboloid, x)
print(f'local minimum is ({x[0]}, {x[1]}), achieved in {k} steps.')

local minimum is (-285.53462448434914, -4922155395233.646), achieved in 8 steps.


In [7]:
x = np.array([1.3, -0.8])
x, k = newton_descent(uneven_paraboloid, x)
print(f'local minimum is ({x[0]}, {x[1]}), achieved in {k} steps.')

local minimum is (-3.8381180422460484e-22, 3.1763735522036263e-22), achieved in 2 steps.


Testing on rosenbrock's function

In [8]:
x = np.array([1.3, -0.8])
x, k = max_descent(rosenbrock, x)
print(f'local minimum is ({x[0]}, {x[1]}), achieved in {k} steps.')

local minimum is (13842676026294.799, 2675394019.4882812), achieved in 2 steps.


In [9]:
x = np.array([1.3, -0.8])
x, k = newton_descent(rosenbrock, x)
print(f'local minimum is ({x[0]}, {x[1]}), achieved in {k} steps.')

local minimum is (0.9999999999370732, 0.9999999998461209), achieved in 7 steps.
